### PR TITLE
[WIP][#39] Submit DanceCritiqueForm functionality

### PR DESCRIPTION
**Pull request by katrinacrisostomo**
Fixes: #39

### CODE REVIEW

**Comment by katrinacrisostomo** [comment]
I'm getting a lint warning saying not to assign to the `DanceCritiqueForm` in the part of the code where I'm connecting the `mapStateToProps`:

```
DanceCritiqueForm = connect(
  DanceCritiqueForm.mapStateToProps,
)(DanceCritiqueForm);
```

But I'm just following how redux-form is saying to do it [here](https://redux-form.com/7.1.2/docs/faq/howtoconnect.md/) 🤔 might just turn off this rule for this instance

**Review by georgeke — DISMISSED** [review]
Looks good. Just for understanding, you wrap dance critique form with `connect` so that its props are supplied from the state in the store right?

I would prefer this get merged ASAP so that I can add on top of it.

**Comment by katrinacrisostomo** [comment]
@georgeke yas exactly

okay, lemme just add a check to make sure the recording saved onto the phone correctly in the `onSubmit`, we probably want to check that too and show an error if it doesn't

**Comment by georgeke** [comment]
@katrinacrisostomo hm the AudioRecorder component doesn't save anything to the store right now. We still have to make a change so that it writes the audio file URI to the store.

**Comment by georgeke** [comment]
also for the lint error I think we can just assign a new variable instead of reassigning the same class (`const DanceCritiqueForm = connect(...)(DanceCritiqueFormInner)`)

**Comment by katrinacrisostomo** [comment]
@georgeke ohh true, okay so I guess I should just merge this and then add that later

**Comment by katrinacrisostomo** [comment]
@georgeke hmmm okay I see, we'll call the class `DanceCritiqueFormInner` and then assign to the new variable and then `export default` on the new variable?

**Comment by katrinacrisostomo** [comment]
@georgeke okay I merge

**Pull request merged**
