### PR TITLE
[WIP][#31] Status item panel

### PR DESCRIPTION
**Pull request by FalahShazib**
I haven't linted or created tests yet. Just wondering if I could make transition smoother. Rn it just appears when clicked

### CODE REVIEW

**Comment by FalahShazib** [comment]
Closed

29426060_1006462226174125_8353447512224301056_o

**Comment by FalahShazib** [comment]
Opened

29433171_1006462212840793_1557428658484805632_o

**Comment by FalahShazib** [comment]
The panel is pretty huge and displaces all the other components. Have to figure out how to overlap

Edit: Not in pushed dancecritique but you can see it as it is supposed to be if you remove all other components. -- not really helpful in big picture work

**Comment by FalahShazib** [comment]
Temporary changes for testing:

- open panel as default
- red background of panel
- yellow background of container

Current issue: Panel will not extend to entire length of screen. Will only grow if statusitems are added

**Comment by FalahShazib** [comment]
To do: Create function concatenating uploaded + not uploaded + filler array. 

Problem: List is not scrollable due to absolute position.

**Review by katrinacrisostomo — APPROVED** [review]

**Pull request merged**
