### PR TITLE
[WIP][Resolves #32] Initial CritiqueSection

### LINKED ISSUE #32: Add CritiqueSection component

### PR DESCRIPTION
**Pull request by jtaaa**
I used PropTypes.func.isRequired for the component prop instead of PropTypes.node.isRequired as suggested because the components were not passing the type checking for node and I read online to type check them as functions.

Fixes #32

### CODE REVIEW

**Comment by georgeke** [comment]
This looks great! So we're passing in the component which will be instantiated by Field, and the component gets additional props from the `prop` prop right?

**Comment by jtaaa** [comment]
Yep that's right @georgeke

**Comment by katrinacrisostomo** [comment]
bitmoji

Lookin good!

What's the `props` object being passed in as an object for? `Field` has to take a `props` prop, is that it?

**Comment by jtaaa** [comment]
Yup! Field takes an optional `props` prop that it passes on to the component props.

**Comment by jtaaa** [comment]
So that's where where you would pass the component's properties

**Review by georgeke — DISMISSED** [review]
Would be cool to a see a screenshot of this in action on the DanceCritique form mimicking one of the critique sections for in the design doc

Other than that, looks good

**Comment by jtaaa** [comment]
Here's a screenshot!
screenshot_20180312-205026

**Review by georgeke — APPROVED** [review]
merge plz

**Pull request merged**
